<?php

/**
 * @file
 * Contains penn_api_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function penn_api_entity_theme() {
  $theme = [];
  $theme['penn_api_entity'] = [
    'render element' => 'elements',
    'file' => 'penn_api_entity.page.inc',
    'template' => 'penn_api_entity',
  ];
  $theme['penn_api_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'penn_api_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function penn_api_entity_theme_suggestions_penn_api_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#penn_api_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'penn_api_entity__' . $sanitized_view_mode;
  $suggestions[] = 'penn_api_entity__' . $entity->bundle();
  $suggestions[] = 'penn_api_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'penn_api_entity__' . $entity->id();
  $suggestions[] = 'penn_api_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
