meta_position.settings:
  type: config_object
  label: 'Meta position settings'
  mapping:
    enabled:
      type: integer
      label: 'Enable the meta position settings'
    node_types:
      type: sequence
      label: 'The node types on which alter the metadata panel position'
      sequence:
        type: string
