_core:
  default_config_hash: R4IF-ClDHXxblLcG1L7MgsLvfBIMAvi_skumNFQwkDc
module:
  mysql: 0
  penn_shortcuts: 0
  simplesamlphp_auth: 0
  structure_sync: 0
  admin_toolbar: 1
  adminimal_admin_toolbar: 1
  automated_cron: 1
  big_pipe: 1
  block: 1
  block_content: 1
  breakpoint: 1
  ckeditor: 1
  color: 1
  comment: 1
  config: 1
  contact: 1
  contextual: 1
  crop: 1
  datetime: 1
  dblog: 1
  devel: 1
  dropzonejs: 1
  dropzonejs_eb_widget: 1
  dynamic_page_cache: 1
  editor: 1
  embed: 1
  emptyparagraphkiller: 1
  entity_browser: 1
  entity_browser_entity_form: 1
  entity_embed: 1
  entity_reference_revisions: 1
  entity_usage: 1
  externalauth: 1
  fences: 1
  field: 1
  field_hidden: 1
  field_ui: 1
  file: 1
  file_mdm: 1
  filter: 1
  google_tag: 1
  help: 1
  history: 1
  image: 1
  image_widget_crop: 1
  imagemagick: 1
  inline_entity_form: 1
  link: 1
  media: 1
  media_entity_browser: 1
  media_library: 1
  menu_link_content: 1
  menu_ui: 1
  meta_position: 1
  metatag: 1
  metatag_facebook: 1
  metatag_open_graph: 1
  metatag_twitter_cards: 1
  metatag_verification: 1
  node: 1
  options: 1
  page_cache: 1
  paragraphs_type_permissions: 1
  path: 1
  path_alias: 1
  penn_api: 1
  penn_api_entity: 1
  penn_ckeditor: 1
  penn_cron: 1
  penn_entity: 1
  penn_search: 1
  quickedit: 1
  rdf: 1
  redis: 1
  search: 1
  shortcut: 1
  simplify_menu: 1
  sophron: 1
  standard: 1
  system: 1
  taxonomy: 1
  text: 1
  token: 1
  toolbar: 1
  tour: 1
  twig_tweak: 1
  update: 1
  user: 1
  views: 1
  views_ui: 1
  xmlsitemap: 1
  paragraphs: 11
theme:
  stable: 1
  bartik: 1
  seven: 1
  penn_global: 1
  adminimal_theme: 1
  penn_starter: 0
profile: standard
