penn_search_label: ''
penn_search_cx: '009002958554749029410:eoogo0or9vg'
search_query_parameter: as_q
_core:
  default_config_hash: BoIwlbQ8tNTv_pmS4S8hSXfT1TeBW2VQtYA2rn_NF3c
actions: null
form_build_id: form-3a7zNPIX2aMdo-EtIztPqFq72tS8hZ0gzERlS18DaZ4
form_token: knxEQ5pVdN3U9LYR7YMsvCZMYSgUzp_4MDM_vukTlms
form_id: penn_search_admin
search_pg_title: 'Search Results'
search_pg_tagline: 'Find information about the people, places and resources that make the University of Pennsylvania unique'
