blocks:
  -
    info: 'Footer Quote'
    langcode: en
    uuid: 2d62d8e4-daa5-4ad4-804e-98d78ecd7fd8
    bundle: basic
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2 class=\"footer__section__title\">Penn's Heritage</h2>\r\n<p><em>As America’s first university, Penn has a history that dates back to 1740 and shares many ties with the colonial city of Philadelphia and the birth of our nation.</em></p>\r\n<a href=\"https://www.upenn.edu/about\" class=\"btn btn--outline-white\">Our History</a>"
          summary: ''
          format: wysiwyg
menus:
  -
    menu_name: footer-utility
    title: 'Contact Us'
    parent: null
    uri: 'https://www.upenn.edu/about/contact'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 60c8d4a6-88d0-4e5e-8798-39af64ddf404
  -
    menu_name: footer-utility
    title: Maps
    parent: null
    uri: 'https://www.facilities.upenn.edu/maps'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 3d5defe0-3b06-41c0-97ee-b88be9941dcd
  -
    menu_name: footer-utility
    title: Parking
    parent: null
    uri: 'https://cms.business-services.upenn.edu/transportation/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 8e47da53-3be3-456b-ab0c-58dd9680a9a2
  -
    menu_name: legal
    title: 'Emergency Services'
    parent: null
    uri: 'https://www.publicsafety.upenn.edu/contact/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: dc60a8e6-dba9-40c6-ac7b-5d7c21da3702
  -
    menu_name: legal
    title: Disclaimer
    parent: null
    uri: 'https://www.upenn.edu/about/disclaimer'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: 7f6901ac-807e-4a1b-ba8f-f9be3c1b5f99
  -
    menu_name: legal
    title: 'Privacy Policy'
    parent: null
    uri: 'https://www.upenn.edu/about/privacy-policy'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: 66369815-4a8c-43de-80c0-f8cce19f728c
  -
    menu_name: legal
    title: 'Report Accessibility Issues and Get Help'
    parent: null
    uri: 'https://accessibility.web-resources.upenn.edu/get-help'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: en
    uuid: 9ff617b6-6829-4ea2-908a-4320438defc4
  -
    menu_name: legal
    title: 'Report Copyright Infringement'
    parent: null
    uri: 'https://www.upenn.edu/about/report-copyright-infringement'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: en
    uuid: 11462be1-afc7-4c79-a4b2-e5ccd85299f0
  -
    menu_name: resources
    title: 'Current Students'
    parent: null
    uri: 'https://portal.apps.upenn.edu/penn_portal/student.php'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: 4753148e-a63e-47b8-92aa-bc0f91fa79aa
  -
    menu_name: resources
    title: 'Faculty & Staff'
    parent: null
    uri: 'https://portal.apps.upenn.edu/penn_portal/u@penn.php'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: 9e0acc78-de02-4cf4-8b69-81ad63363f33
  -
    menu_name: resources
    title: Parents
    parent: null
    uri: 'https://www.upenn.edu/parents'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: c764b79f-70ec-4630-99f8-4dc07e369f8a
  -
    menu_name: resources
    title: Alumni
    parent: null
    uri: 'https://www.alumni.upenn.edu'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-47'
    langcode: en
    uuid: 0a00faeb-7d1d-46db-856c-dffed5273758
  -
    menu_name: resources
    title: Visitors
    parent: null
    uri: 'https://www.upenn.edu/visitors'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: en
    uuid: 652b1dad-cc44-4869-8912-813750f95d74
  -
    menu_name: resources
    title: A-Z
    parent: null
    uri: 'https://www.upenn.edu/penn-a-z'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: en
    uuid: 3a4a206a-8951-4374-baca-743fc8784d5e
  -
    menu_name: resources
    title: Directory
    parent: null
    uri: 'https://www.upenn.edu/directories'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-44'
    langcode: en
    uuid: 6166bc88-2ef4-4237-afa4-070c029f9fc5
  -
    menu_name: resources
    title: Webmail
    parent: null
    uri: 'https://provider.www.upenn.edu/computing/webmail/index.php'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-43'
    langcode: en
    uuid: 36dd23c4-47c5-4718-b539-8b9ca096cca1
  -
    menu_name: resources
    title: Services
    parent: null
    uri: 'https://www.upenn.edu/services'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-42'
    langcode: en
    uuid: 7814dcaf-02bd-4654-a8ec-b62b7fb6a85f
  -
    menu_name: navigation
    title: About
    parent: null
    uri: 'https://www.upenn.edu/about'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: en
    uuid: defe4d0b-900a-437b-8422-01e429ed8baf
  -
    menu_name: footer-links
    title: Athletics
    parent: null
    uri: 'https://pennathletics.com/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: a2fbfa82-c489-4bd9-a0e9-e953df09e5c7
  -
    menu_name: footer-links
    title: Diversity
    parent: null
    uri: 'https://diversity.upenn.edu/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: be5a3e51-879f-4ab5-8ded-97818875273c
  -
    menu_name: footer-links
    title: 'Health Care'
    parent: null
    uri: 'https://www.upenn.edu/life-at-penn/health-and-wellness'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 1dff2ca1-e18d-4db4-9188-870f969cd7ba
  -
    menu_name: footer-links
    title: Libraries
    parent: null
    uri: 'https://www.library.upenn.edu/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 0070d75f-868c-49f4-a364-ce5830b2d594
  -
    menu_name: footer-links
    title: 'Online Learning'
    parent: null
    uri: 'https://www.onlinelearning.upenn.edu/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 606a15d0-2931-4983-8382-cf5403f1523e
  -
    menu_name: footer-links
    title: 'Penn Global'
    parent: null
    uri: 'https://global.upenn.edu/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: cddccd2e-0cc2-41c2-81e1-5c64c23a53ad
  -
    menu_name: footer-links
    title: Alumni
    parent: null
    uri: 'https://www.alumni.upenn.edu'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: c951ed23-b9df-4647-9cdb-66a57e951124
