_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 711fc159-acb4-48b6-ad92-559179390c68
name: 'Set name in settings.php'
mail: haasj@upenn.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
